version: '3'

services:

  ionic:
    image: node
    command: bash -c 'npm install && npm run build'
    working_dir: /build
    volumes:
      - /build/node_modules
      - ./ionic:/build
      - ./dist/www:/dist/www

  cordova:
    command: bash -c 'npm install && npm run build'
    environment:
      - CI=true
    image: beesden/cordova
    working_dir: /build
    volumes:
      - /build/node_modules
      - ./cordova:/build
      - ./dist/platforms:/build/platforms
      - ./dist/www:/build/www

  android_debug:
    command: gradle assembleDebug
    image: beesden/android
    working_dir: /build/android
    volumes:
      - gradle:/root/.gradle
      - ./dist/android:/build/android/app/build/outputs/apk
      - ./dist/platforms:/build

  android_release:
    command: gradle assembleRelease
    image: beesden/android
    working_dir: /build/android
    volumes:
      - gradle:/root/.gradle
      - ./dist/android:/build/android/app/build/outputs/apk
      - ./dist/platforms:/build

volumes:
  gradle:
