version: '3'

services:

  app:
    build:
      context: ./app
    command: ['ionic',  'serve']
    volumes:
      - www:/build/www

  cordova:
    command: npm install --unsafe-perm
    image: beesden/cordova
    working_dir: /build
    volumes:
      - ./cordova:/build
      - /build/node_modules
      - platforms:/build/platforms

volumes:
  platforms:
  www:
